### ISSUE TITLE
Livestream UI should look different if notes do not exist

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#192] opened 2020-12-28 22:49 UTC
Example: Christmas Eve service. The UI should not include the notes header since there aren't any notes.

Probably just the live video makes the most sense.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=615351086)

**Comment by lucastbelem** [comment] 2021-01-22 18:36
duplicate of #149

**Closed as completed by lucastbelem** 2021-01-22 18:36 UTC
