### ISSUE TITLE
Unable to set location

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#205] opened 2021-01-07 00:53 UTC
I'm getting the following error when starting the app:
``[ERROR] 46:34.231 AWSPinpointProvider - updateEndpoint failed, [BadRequestException: Exceeded maximum endpoint per user count: 10]``
Not sure if it's related but I am unable to set a different location.
Is anyone else getting this?

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=618978590)

**Comment by JonEsparaz** [comment] 2021-01-07 01:20
I don't get the error. I checked in AWS, looks like your Cognito identity has more than 10 devices associated with it (which is what the error says too).

I assume this has something to do with your development setup. Is it possible that your local storage is cleared very frequently? Or are you using several VMs or something like that?

**Comment by itbel** [comment] 2021-01-07 01:25
I recently got a new computer set up, and have been switching back and forth between devices/ reinstalling OS's. Any idea on how I can fix this?

**Comment by JonEsparaz** [comment] 2021-01-07 01:31
I'm not sure. We might need to reset your account or remove the devices. @GeorgeBellTMH?

Regarding the location selection issue, I too have this problem. Looks like I broke something in #198 - will fix shortly.

**Comment by georgevicbell** [comment] 2021-01-07 06:17
Looks like its a regression in Amplify, I think if we upgrade it might resolve...


George Bell
Cell: 416-802-6697

________________________________

**Closed as completed** 2021-01-11 15:27 UTC
Labels: question
